<?php
/** Created by griga at 15.07.2014 | 13:27.
 * 
 */

class SeoConfigController extends BackendController{


    protected function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function actionList()
    {
        $models = SeoConfig::model()->multilang()->findAll();
        $this->renderJson(JSONUtil::convertModelToArray($models,
            ['{{seo_config}}'=>'id, key, value, value_ru, value_uk, value_en']
        ));
    }

    /**
     *
     */
    public function actionView($id)
    {
        $model = SeoConfig::model()->multilang()->findByPk($id);

        $this->renderJson(JSONUtil::convertModelToArray($model,
            ['{{seo_config}}'=>'id, key, value, value_ru, value_uk, value_en']
        ));
    }

    public function actionUpdate($id){
        $model = SeoConfig::model()->multilang()->findByPk($id);
        $model->attributes = $this->inputJson();
        if($model->save()){
            $this->renderJson(['success'=>true]);
        } else {
            $this->renderJson(['errors'=>$model->errors]);
        }
    }

    public function actionCreate(){
        $model = new SeoConfig();
        $model->attributes = $this->inputJson();
        if($model->save()){
            $this->renderJson(['success'=>true]);
        } else {
            $this->renderJson(['errors'=>$model->errors]);
        }
    }



} 